<?php

namespace DoctrineORMModule\Proxy\__CG__\Users\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Users extends \Users\Entity\Users implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'id', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'firstname', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'lastname', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'birthday', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'email', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'role', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'blacklist', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'avatar', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'password', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'token', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'gotKey', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'gotRemote'];
        }

        return ['__isInitialized__', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'id', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'firstname', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'lastname', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'birthday', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'email', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'role', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'blacklist', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'avatar', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'password', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'token', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'gotKey', '' . "\0" . 'Users\\Entity\\Users' . "\0" . 'gotRemote'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Users $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname(string $firstname): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname(string $lastname): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$birthday]);

        parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole(string $role): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isBlacklist(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlacklist', []);

        return parent::isBlacklist();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlacklist(bool $blacklist): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlacklist', [$blacklist]);

        parent::setBlacklist($blacklist);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', []);

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar(?string $avatar): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', [$avatar]);

        parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken(?string $token): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getGotKey(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGotKey', []);

        return parent::getGotKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setGotKey(?bool $gotKey): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGotKey', [$gotKey]);

        parent::setGotKey($gotKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getGotRemote(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGotRemote', []);

        return parent::getGotRemote();
    }

    /**
     * {@inheritDoc}
     */
    public function setGotRemote(bool $gotRemote): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGotRemote', [$gotRemote]);

        parent::setGotRemote($gotRemote);
    }

}
