<div class="card mt-4">
    <h4>Modifier un utilisateur</h4>

    <form method="post" class="mt-3">
        <div class="row">
            <div class="form-group col-sm-3 mt-3">
                <label for="first_name">Prénom</label>
                <input type="text"
                       class="form-control"
                       name="first_name"
                       id="first_name"
                       value="<?= $this->escapeHtmlAttr($user->getFirstname()) ?>"
                       required>
            </div>

            <div class="form-group col-sm-3 mt-3">
                <label for="last_name">Nom</label>
                <input type="text"
                       class="form-control"
                       name="last_name"
                       id="last_name"
                       value="<?= $this->escapeHtmlAttr($user->getLastname()) ?>"
                       required>        
            </div>  
            <div class="form-group col-sm-3 mt-3">
                <label for="email">Email</label>
                <input type="email"
                       class="form-control"
                       name="email"
                       id="email"
                       value="<?= $this->escapeHtmlAttr($user->getEmail()) ?>"
                       required>
            </div>
            <div class="form-group d-flex justify-content-between mt-3">
                <div class='col-3'>
                    <label for="status">Admin</label>
                    <select class="form-control" name="isAdmin" id="isAdmin">
                        <option value="1" <?= $user->getIsAdmin() == 1 ? 'selected' : '' ?>>Oui </option>
                        <option value="0" <?= $user->getIsAdmin() == 0 ? 'selected' : '' ?>>Non</option>
                    </select>
                </div>
                <div class='col-3'>
                    <label for="status">Membre</label>
                    <select class="form-control" name="isMember" id="isMember">
                        <option value="1" <?= $user->getIsMember() == 1 ? 'selected' : '' ?>>Oui </option>
                        <option value="0" <?= $user->getIsMember() == 0 ? 'selected' : '' ?>>Non</option>
                    </select>
                </div>
                <div class='col-3'>
                    <label for="status">Blacklist</label>
                    <select class="form-control" name="isMember" id="isMember">
                        <option value="1" <?= $user->getIsBlacklist() == 1 ? 'selected' : '' ?>>Oui </option>
                        <option value="0" <?= $user->getIsBlacklist() == 0 ? 'selected' : '' ?>>Non</option>
                    </select>
                </div>
        
            </div>
        </div>

        <div class='d-flex justify-content-between mt-5 '>
            <div class="form-group ">
                <button type="submit" class="btn btn-warning">Enregistrer</button>
                <a href="<?= $this->url('admin-games') ?>" class="btn btn-secondary">Annuler</a>    
            </div>
        </form>
            <div class="form-group">
                <form method="post" action="<?= $this->url('admin-delete-user');?>" class="delete-form ">
                    <input type="hidden" name="iduser" value="<?= $user->getIduser()?>">
                    <button type="button" class="btn btn-danger btn-delete" data-id="<?= $user->getIduser() ?>">
                            Supprimer
                    </button>
                </form>
            </div>
        </div>
</div>




<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" id="confirmDeleteForm">
                <div class="modal-header">
                <h5 class="modal-title">Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
                </div>
                <div class="modal-body">
                Êtes-vous sûr de vouloir désactiver ce joueur ?
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <button type="submit" class="btn btn-danger">Confirmer</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script src="/js/pages/admin/edit-user.js"></script>