<div class='card'>
  <h3>Utilisateurs</h3>
  <table id="userTable" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user): ?>
      <tr>
        <td><?= $this->escapeHtml($user->getLastname()) ?></td>
        <td><?= $this->escapeHtml($user->getFirstname()) ?></td>
        <td>
          <a href="<?= $this->url('admin-edit-user', ['iduser' => $user->getIdUser()]) ?>" class="btn btn-sm btn-warning">
            <i class="fa-solid fa-edit"></i>
          </a>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
</div>