<?php if ($this->message): ?>
    <div class="alert alert-danger"><?= $this->escapeHtml($this->message) ?></div>
<?php endif; ?>

<div class='card'>
    <h4> Connexion </h4>
<div class="row">
    <div class="col-lg-6 col-sm-12">
        <form method="post" action="">
            <div class="form-group">
                <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
            </div>

            <div class="form-group mt-3">
                <label for="password">Mot de passe</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Mot de passe" required>
            </div>

            <button type="submit" class="btn btn-primary mt-4 w-50">Se connecter</button>
        </form>

        <?php if (!empty($message)): ?>
            <div class="alert alert-danger mt-3"><?= $this->escapeHtml($message) ?></div>
        <?php endif; ?>
    </div>
</div>

</div>

