<?php if ($this->message): ?>
    <div class="alert alert-danger"><?= $this->escapeHtml($this->message) ?></div>
<?php endif; ?>
<h4> Connexion </h4>
<div class="row">
    <div class="col-lg-6 col-sm-12">
        <form method="post">
            <?= $this->form()->openTag($form) ?>
            <?= $this->formLabel($form->get('email')) ?>
            <?= $this->formElement($form->get('email')) ?>
            <?= $this->formLabel($form->get('password')) ?>
            <?= $this->formElement($form->get('password')) ?>
            <button type="submit" class=" mt-3">Se connecter</button>
            <?= $this->form()->closeTag() ?>
        </form>
    </div>
</div>    


