<?php if ($this->message): ?>
    <div class="alert alert-danger"><?= $this->escapeHtml($this->message) ?></div>
<?php endif; ?>

<div class='card'>
    <h4> Mot de passe oublié </h4>



<?php if($this->user): ?>
<div class="row">
    <div class="col-lg-6 col-sm-12">
        <p>Veuillez entrer votre nouveau mot de passe.</p>
    </div> 
</div>
<div class="row">
    <div class="col-lg-6 col-sm-12">
        <form method="post" action="">
            <div class="form-group">
                <input type="new-password" class="form-control" name="new-password" id="new-password" placeholder="Nouveau mot de passe" required>
                <input type="hidden" name="token" value="<?= $this->escapeHtml($this->user->getResetToken()) ?>">  
                <input type="hidden" name="email" value="<?= $this->escapeHtml($this->user->getEmail()) ?>">
            </div>
            <button type="submit" class="btn btn-warning mt-4 w-50">Réinitialiser</button>
        </form>
        <?php if (!empty($message)): ?>
            <div class="alert alert-danger mt-3"><?= $this->escapeHtml($message) ?></div>
        <?php endif; ?> 
    </div>
</div>

    <?php else: ?>

<div class="row">
    <div class="col-lg-6 col-sm-12">
        <form method="post" action="">
            <div class="form-group">
                <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
            </div>
            <button type="submit" class="btn btn-warning mt-4 w-50">Réinitialiser</button>
        </form>
        <?php if (!empty($message)): ?>
            <div class="alert alert-danger mt-3"><?= $this->escapeHtml($message) ?></div>
        <?php endif; ?> 
    </div>
</div>

<?php endif; ?>



</div>

