<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <favicon rel="icon" type="image/png" href="/images/favicon.png">
    <title>Maintenance en cours</title>
    <style>
        body {
            background-color: #000;
            color: white;
            font-size:large;
            font-family: 'Courier New', Courier, monospace;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            text-align: center;
            flex-direction: column;
        }
      
    </style>
</head>
<body>
    <div class="container">
        <img src="/images/logo.png" alt="503 Service Unavailable" style="width:200px;height:auto;">
    </div>
    <div style='margin:15px;'>
       Le site est en cours de maintenance.
       Merci de revenir plus tard! 
    </div>
</body>
</html>
