<link rel="stylesheet" href="/css/pages/profil-index.css">
<div class="tab-nav-wrapper">
  <div class="tab-nav-scroll">
    <ul class="tab-nav">
      <li><a href="#" class="tab-link active" data-tab="profil">Mon profil</a></li>
      <li><a href="#" class="tab-link" data-tab="arsenal">Mon arsenal</a></li>
    </ul>
  </div>
 </div>
<div id="tabContent" class="mt-3">
  <div>Chargement...</div>
</div>

<script src="/js/pages/profil/index.js"></script>
