
<div class='card'>
    <div class='row'>
        <div class="col-6" >
            <h5><?= $this->escapeHtml($currentUser->getLastName()) ?> <?= $this->escapeHtml($currentUser->getFirstName()) ?></h5>
            <h6><?= $this->escapeHtml($currentUser->getNickname()) ?></h6>
            <p  class="m-0"><?= $this->escapeHtml($currentUser->getBirthdate()->format('d/m/Y')) ?></p>
            <p class="m-0"><?= $this->escapeHtml($currentUser->getEmail()) ?></p>
        </div>
        <div class="col-6" >
            <div class="col-12">
                <a href="<?= $this->escapeHtmlAttr($this->url('profil-edit', ['id' => $currentUser->getIduser()])) ?>" class="btn btn-warning mt-3 w-100">
                    Modifier Profil
                </a>
            </div>
            <div class="col-12">
             <!--    <a href="<?= $this->escapeHtmlAttr($this->url('faction')) ?>" class="btn btn-warning mt-3 w-100">
                   Faction
                </a>
            </div>
           <div class="col-12">
                <a href="<?= $this->escapeHtmlAttr($this->url('arsenal')) ?>" class="btn btn-warning mt-3 w-100">
                    Mon arsenal
                </a>
            </div> -->
        </div>
    </div>         
       <div class='row'>
            <div class="col-12"> 
                <div>
                    <a class="btn btn-warning mt-5" href="<?= $this->escapeHtmlAttr($this->url('logout')) ?>">Se déconnecter</a>
                </div>   
            </div>   
            <div class="col-12">
                <div>
                    <a class="btn btn-warning mt-3" href="<?= $this->escapeHtmlAttr($this->url('logout')) ?>">Réinitialiser Mot de passe</a>
                </div>
            </div>
        </div>
</div>

<?php if ($registers): ?>
    <div class='card'>
        <h4>Mes parties jouées</h4>
        <?php foreach ($registers as $register): ?>
            <?php
                $game = $register->getGame();
                $dateFolder = $game->getDate()->format('d-m-Y');
                $photoDir = 'public/photos/games/' . $dateFolder;
                // dump($photoDir);
                $hasPhotos = is_dir($photoDir) && count(
                    array_filter(scandir($photoDir), function ($file) use ($photoDir) {
                        return preg_match('/\.(jpg|jpeg|png|gif)$/i', $file) && is_file($photoDir . '/' . $file);
                    })
                ) > 0;
            ?>
            <hr>
            <p>
                <?= $this->escapeHtml($game->getDate()->format('d/m/Y')) ?>
                <?php if ($hasPhotos): ?>
                    <a href="<?= $this->escapeHtmlAttr($this->url('photos-view', ['date' => $dateFolder, 'type'=>'games'])) ?>" class="btn btn-sm btn-secondary ms-2">
                        Voir les photos
                    </a>
                <?php endif; ?>
            </p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
