
<div class='card'>
    <div class='row'>
        <div class="col-6" >
            <h5><?php echo $currentUser->getLastName();?> <?php echo $currentUser->getFirstName();?></h5>
            <h6><?php echo $currentUser->getNickname();?></h6>                    
            <p  class="m-0"><?php echo $currentUser->getBirthdate()->format("d/m/Y");?></p>
            <p class="m-0"><?php echo $currentUser->getEmail();?></p>
        </div>
        <div class="col-6" >
            <div class="col-12">
                <a href="<?= $this->url('profil-edit', ['id' => $currentUser->getIduser()]) ?>" class="btn btn-warning mt-3 w-100">
                    Modifier Profil
                </a>
            </div>
            <div class="col-12">
                <a href="<?= $this->url('arsenal') ?>" class="btn btn-warning mt-3 w-100">
                    Mon arsenal
                </a>
            </div>
        </div>
    </div>         
       <div class='row'>
            <div class="col-12"> 
                <div>
                    <button class="btn btn-warning mt-5" onclick="window.location.href='<?= $this->url('logout') ?>'">Se déconnecter</button>
                </div>   
            </div>   
            <div class="col-12">
                <div>
                    <button class="btn btn-warning mt-3" onclick="window.location.href='<?= $this->url('logout') ?>'">Réinitialiser Mot de passe</button>
                </div>
            </div>
        </div>
</div>