<div class="card mt-4">
    <h4>Modifier un utilisateur</h4>

    <form method="post" class="mt-3">
        <div class="row">
            <div class="form-group col-sm-3">
                <label for="first_name">Prénom</label>
                <input type="text"
                       class="form-control"
                       name="first_name"
                       id="first_name"
                       value="<?= $this->escapeHtmlAttr($user->getFirstname()) ?>"
                       required>
            </div>

            <div class="form-group col-sm-3">
                <label for="last_name">Nom</label>
                <input type="text"
                       class="form-control"
                       name="last_name"
                       id="last_name"
                       value="<?= $this->escapeHtmlAttr($user->getLastname()) ?>"
                       required>        
            </div>  
            <div class="form-group col-sm-3">
                <label for="email">Email</label>
                <input type="email"
                       class="form-control"
                       name="email"
                       id="email"
                       value="<?= $this->escapeHtmlAttr($user->getEmail()) ?>"
                       required>
            </div>
            <div class="form-group col-sm-3">
                <label for="status">Admin</label>
                <select class="form-control" name="isAdmin" id="isAdmin">
                    <option value="1" <?= $user->getIsAdmin() == 1 ? 'selected' : '' ?>>Oui </option>
                    <option value="0" <?= $user->getIsAdmin() == 0 ? 'selected' : '' ?>>Non</option>
                </select>
            </div>
        </div>
        <div class="form-group mt-3">
            <button type="submit" class="btn btn-warning">Enregistrer</button>
            <a href="<?= $this->url('admin-games') ?>" class="btn btn-secondary">Annuler</a>    
        </div>
    </form>
</div>