<link rel="stylesheet" href="/css/pages/Game-index.css">
<div class='row'>
 
</div>

<div>
    <h3>Les parties</h3>

    <table id="repliqueTable" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Date</th>
            <th>Player MAx</th>
            <th>Satus</th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

    
<h4>Ajouter une partie</h4>


<?php
$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="row">

    <div class="form-group col-sm-2">
        <?= $this->formLabel($form->get('date')) ?>
        <?= $this->formElement($form->get('date')) ?>
        <?= $this->formElementErrors($form->get('date')) ?>
    </div>

    <div class="form-group col-sm-4">
        <?= $this->formLabel($form->get('player_max')) ?>
        <?= $this->formElement($form->get('player_max')) ?>
        <?= $this->formElementErrors($form->get('player_max')) ?>
    </div>

    <div class="form-group col-sm-4 mb-3">
        <?= $this->formLabel($form->get('status')) ?>
        <?= $this->formElement($form->get('status')) ?>
        <?= $this->formElementErrors($form->get('status')) ?>
    </div>

    <div class="form-group col-sm-6">
        <?= $this->formElement($form->get('submit')) ?>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>



<script src="js/pages/admin-game-index.js"></script>
