<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Faction </title>
    <!-- <link rel="stylesheet" href="/assets/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="/assets/css/faction.css">
</head>
<body>



<!-- Main content area -->
<div class="faction-content">
    <?php if (isset($this->flashMessenger)) : ?>
        <?= $this->flashMessenger()->render() ?>
    <?php endif; ?>

    <?= $this->content; ?>
    <div class="scanline"></div>

</div>
<script src="/assets/js/faction.js"></script>

</body>

</html>
